### ISSUE TITLE
NuGet?

### ISSUE THREAD

**Issue by weitzhandler** [Oceanware/OceanForXamarinForms#1]
I'm currently working on a XF and validation is still a nightmare.
Your example shows a good way (I wish XF adopts!) of implementing validation in an efficient manner.
Validation should pop up from the VM and barely be mentioned in the View.
Do you think about making an external repo that supports validation for XF as a nuget package?

**Comment by kdawg1406** [comment]
@weitzhandler 

I could, but was thinking it would be better to have developers use the library, learn from the code and mold it to their needs or project needs.

I've created an update and will upload the new repo with the two Ocean libraries in .NET Standard libraries.  Then you could easily download, add to your project.

Would this work for you?

Best,

Karl

**Comment by weitzhandler** [comment]
You're asking me 'Would this work for you' like you owe me anything...
Anyway, anything would work. I thought dividing those libraries into standalone libraries, e.g. validation library only, and posting on nuget, would attract more real-life users to actually use and improve the library itself instead of each one forking their own solution and keep their ideas private.

Thank you!

**Comment by kdawg1406** [comment]
@weitzhandler , OK will do.  I'll do it this week.

**Comment by weitzhandler** [comment]
Thank you, something like Xamarin.Forms.Validation etc.
